# Script for reporting indoor/outdoor temperature to the controller from any home assistant sensor
# Updated: 07.12.2023

alias: Report temp to controller
description: ""
variables:
  # The source sensor from which we take the temperature
  source_entity: "sensor.livingroom_temperature"

  # Target entity number where we set the temperature
  # To report indoor temperature: number.opentherm_indoor_temp
  # To report outdoor temperature: number.opentherm_outdoor_temp
  target_entity: "number.opentherm_indoor_temp"
trigger:
  - platform: time_pattern
    seconds: /30
condition:
  - condition: template
    value_template: "{{ states(source_entity) != 'unavailable' and states(target_entity) != 'unavailable' }}"
action:
  - if:
      - condition: template
        value_template: "{{ (states(source_entity)|float(0) - states(target_entity)|float(0)) | abs | round(2) >= 0.01 }}"
    then:
      - service: number.set_value
        data:
          value: "{{ states(source_entity)|float(0)|round(2) }}"
        target:
          entity_id: "{{ target_entity }}"
mode: single