# Script for reporting outdoor temperature to the controller from home assistant weather integration
# Updated: 07.12.2023

alias: Report outdoor temp to controller from weather
description: ""
variables:
  # The source weather from which we take the temperature
  source_entity: "weather.home"

  # Target entity number where we set the temperature
  # If the prefix has not changed, then you do not need to change it
  target_entity: "number.opentherm_outdoor_temp"
trigger:
  - platform: time_pattern
    seconds: /30
condition:
  - condition: template
    value_template: "{{ states(source_entity) != 'unavailable' and states(target_entity) != 'unavailable' }}"
action:
  - if:
      - condition: template
        value_template: "{{ (state_attr(source_entity, 'temperature')|float(0) - states(target_entity)|float(0)) | abs | round(2) >= 0.1 }}"
    then:
      - service: number.set_value
        data:
          value: "{{ state_attr(source_entity, 'temperature')|float(0)|round(2) }}"
        target:
          entity_id: "{{ target_entity }}"
mode: single