alias: Set boiler outdoor temp
description: ""
trigger:
  - platform: state
    entity_id:
      - weather.home
    attribute: temperature
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - platform: time_pattern
    seconds: /30
condition: []
action:
  - if:
      - condition: template
        value_template: "{{ has_value('weather.home') and (state_attr('weather.home', 'temperature')|float(0) - states('number.opentherm_outdoor_temp')|float(0)) | abs | round(2) >= 0.1 }}"
    then:
      - service: number.set_value
        data:
          value: "{{ state_attr('weather.home', 'temperature')|float(0)|round(2) }}"
        target:
          entity_id: number.opentherm_outdoor_temp
mode: single